apiVersion: v1
kind: Namespace
metadata:
  name: teste-echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: teste-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: registry.k8s.io/echoserver:1.4
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-svc
  namespace: teste-echo
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echoserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver-ingress
  namespace: teste-echo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cf
spec:
  ingressClassName: nginx
  rules:
  - host: "echo.o-br1.banana.games" 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserver-svc
            port:
              number: 80
  tls:
  - hosts:
    - "echo.o-br1.banana.games"  
    secretName: echo-tls-secret